SELECT I.SUMMARY, L.NAME
FROM ISSUES I
JOIN ISSUESLISTS L ON L.ID = I.ISSUESLIST_ID;

SELECT I.SUMMARY, U.FIRSTNAME, U.LASTNAME
FROM ISSUES I
JOIN USERS U ON I.USER_ID_ASSIGNEDTO = U.ID;

SELECT I.SUMMARY, U.FIRSTNAME, U.LASTNAME, COUNT(*) AS ISSUE_NUMBER
FROM ISSUES I
JOIN USERS U ON I.USER_ID_ASSIGNEDTO = U.ID
GROUP BY I.USER_ID_ASSIGNEDTO;
