USE kodilla_tester;
DROP TABLE IF EXISTS POSTS;

CREATE TABLE POSTS
(
    ID          SERIAL PRIMARY KEY,
    USER_ID     BIGINT UNSIGNED NOT NULL,
    BODY        VARCHAR(1024),
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

INSERT INTO POSTS (USER_ID, BODY)
VALUES (1, "This is my first post on this forum!");

COMMIT;

SELECT * FROM POSTS;

INSERT INTO POSTS (USER_ID, BODY) VALUES (1, "Hello everybody");

INSERT INTO POSTS (USER_ID, BODY) VALUES (5, "Hello, I am Thomas");

INSERT INTO POSTS (USER_ID, BODY) VALUES (6, "Hi, I am John");

COMMIT;

UPDATE POSTS
SET BODY = "To delete"
WHERE ID = 7;

UPDATE POSTS
SET BODY = "To delete"
WHERE ID = 8;

UPDATE POSTS
SET BODY = "To delete"
WHERE ID = 9;

COMMIT;

DELETE FROM POSTS
WHERE ID = 7;

DELETE FROM POSTS
WHERE ID = 8;

DELETE FROM POSTS
WHERE ID = 9;

COMMIT;

SELECT * FROM POSTS;
